version: '3'
services:
    postgres-django-gramm:
      image: postgres:15.2-alpine
      restart: always
      container_name: postgres-django-gramm
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - "${DB_PORT}:${DB_PORT}"
      volumes:
        - PGdata:/var/lib/postgresql/data

volumes:
    PGdata: